import os
import json
import time

from .ingest import extract_audio
from .preprocess import segment_audio
from .analyze import extract_acoustic_features
from .emotion_map import map_features_to_emotion
from .transcribe_translate import TranslationService
from .synthesize import synthesize_speech
from .align import align_prosody
from .evaluate import evaluate_metrics

class DubbingOrchestrator:
    def __init__(self, input_path: str, target_lang: str = "Spanish", output_dir: str = "results"):
        self.input_path = os.path.abspath(input_path)
        self.target_lang = target_lang
        self.output_dir = os.path.abspath(output_dir)
        os.makedirs(self.output_dir, exist_ok=True)
        self.translator = None # Lazy load

    def run(self):
        print("=" * 70)
        print("  Emotion-Preserving AI Video Dubbing -- Modular Pipeline")
        print("=" * 70)
        t_start = time.time()

        # 1. Ingest
        source_audio = extract_audio(self.input_path, self.output_dir)

        # Grab total source duration for assembly canvas
        import librosa
        import numpy as np
        y_src, sr = librosa.load(source_audio, sr=16000, mono=True)
        total_source_duration = len(y_src) / sr
        
        # 2. Preprocess (Chunking stub)
        segments = segment_audio(source_audio, self.output_dir)

        # 3. Analyze MIR (running on first segment for now to establish baseline V-A)
        # In the future, this should aggregate across all segments.
        features = extract_acoustic_features(segments[0])

        # 4. Map Emotion
        valence, arousal = map_features_to_emotion(features)

        # Process all segments
        self.translator = TranslationService()
        dubbed_segments = []
        is_demo_run = False
        
        # Source Classification for Experimental Honesty
        input_fn = os.path.basename(self.input_path).lower()
        if "speech_sample.wav" in input_fn or "synthetic" in input_fn or "gtts" in input_fn or "real_human_speech.wav" in input_fn:
            source_type = "Synthetic Speech / TTS"
        elif "audio.aac" in input_fn or "video.mp4" in input_fn or "beep" in input_fn:
            source_type = "Non-Speech / Dummy"
        else:
            source_type = "Human Speech (Provisionally Validated)"

        manifest = {
            "source_type": source_type,
            "source_duration_s": round(total_source_duration, 2),
            "segments_processed": len(segments),
            "segments": []
        }
        
        # Load the segmentation metadata generated by preprocess.py
        with open(os.path.join(self.output_dir, "segments.json"), "r") as f:
            seg_meta = json.load(f)

        for i, seg in enumerate(segments):
            print(f"--- Processing Segment {i+1}/{len(segments)} ---")
            transcript, demo_trans = self.translator.transcribe(seg, self.output_dir)
            translation, demo_transl = self.translator.translate(transcript, self.target_lang, self.output_dir)
            
            if demo_trans or demo_transl:
                is_demo_run = True
                
            # Synthesize (using ElevenLabs / gTTS)
            dub_filename = f"dubbed_segment_{i}.wav"
            dubbed = synthesize_speech(translation, valence, arousal, self.output_dir, output_filename=dub_filename)
            dubbed_segments.append(dubbed)
            
            # Record manifest history
            start_s = 0.0
            src_dur = 0.0
            if seg_meta["segments"] and i < len(seg_meta["segments"]):
                start_s = seg_meta["segments"][i]["start_s"]
                src_dur = seg_meta["segments"][i].get("end_s", 0) - start_s
                
            manifest["segments"].append({
                "source_segment": seg,
                "dubbed_segment": dubbed,
                "start_s": start_s,
                "source_duration_s": round(src_dur, 2),
                "transcript": transcript,
                "translation": translation,
                "transcript_mode": "Fallback" if demo_trans else "Real",
                "translation_mode": "Fallback" if demo_transl else "Real",
                "synthesis_mode": "TTS",
                "segment_validity": "Invalid/Demo" if (demo_trans or demo_transl) else "Valid",
                "is_demo_fallback": (demo_trans or demo_transl),
                "contributed_to_assembly": True
            })

        # Assemble the full dubbed track
        print("[ASSEMBLY] Reconstructing discrete target timeline payload...")
        # Since durations differ radically between languages, concatenating loosely 
        # is temporally corrupting, but putting them at their specific start times maintains order natively.
        assembled_audio = np.zeros(int((total_source_duration + 5.0) * 16000), dtype=np.float32) 
        
        current_cursor = 0
        for i, dub_path in enumerate(dubbed_segments):
            y_dub, _ = librosa.load(dub_path, sr=16000, mono=True)
            dub_dur = len(y_dub) / 16000
            manifest["segments"][i]["dubbed_duration_s"] = round(dub_dur, 2)
            
            if seg_meta["segments"] and i < len(seg_meta["segments"]):
                start_s = seg_meta["segments"][i]["start_s"]
                insert_idx = int(start_s * 16000)
                # If we overlap due to bad duration expansions, push safely forward.
                if insert_idx < current_cursor:
                    insert_idx = current_cursor
            else:
                insert_idx = current_cursor
            
            end_idx = insert_idx + len(y_dub)
            # extend array native capacity dynamically if the translation is insanely long
            if end_idx > len(assembled_audio):
                assembled_audio = np.pad(assembled_audio, (0, end_idx - len(assembled_audio) + 16000))
                
            assembled_audio[insert_idx:end_idx] += y_dub
            current_cursor = end_idx + 4000 # add 250ms spacing minimum
            
        full_dubbed_path = os.path.join(self.output_dir, "dubbed_audio.wav")
        import soundfile as sf
        sf.write(full_dubbed_path, assembled_audio[:current_cursor], 16000)
        
        manifest["assembled_file"] = full_dubbed_path
        with open(os.path.join(self.output_dir, "segment_manifest.json"), "w") as f:
            json.dump(manifest, f, indent=2)

        dubbed_audio = full_dubbed_path

        # 7. Align
        align_info = align_prosody(source_audio, dubbed_audio)

        # 8. Evaluate
        metrics = evaluate_metrics(source_audio, dubbed_audio, self.output_dir)
        
        # Merge summary
        metrics["valence"] = valence
        metrics["arousal"] = arousal
        metrics["alignment_info"] = align_info
        metrics["is_demo_run"] = is_demo_run
        
        # 8. Experimental Run Validity Conclusion
        # Valid: Real Human Source + API Intelligence successfully applied.
        # Synthetic Baseline: Synthetic Source + API Intelligence successfully applied.
        # Invalid/Demo: Fallback/Demo content used anywhere in the timeline.
        # Invalid/NonSpeech: Source is non-vocal.

        if is_demo_run:
            run_validity = "Invalid/Demo"
        elif manifest["source_type"] == "Synthetic Speech / TTS":
            run_validity = "Synthetic Baseline"
        elif manifest["source_type"] == "Non-Speech / Dummy":
            run_validity = "Invalid/NonSpeech"
        else:
            run_validity = "Valid"
        
        metrics["run_validity"] = run_validity

        # 9. Output State
        state_path = os.path.join(self.output_dir, "pipeline_results.json")
        with open(state_path, "w", encoding="utf-8") as f:
            json.dump(metrics, f, indent=2)

        # 10. Write run_summary.txt
        summary_path = os.path.join(self.output_dir, "run_summary.txt")
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write("=== PIPELINE RUN SUMMARY ===\n")
            f.write(f"Input Used: {self.input_path} (Detected Profile: {manifest['source_type']})\n")
            f.write(f"Transcript Mode: {'Fallback Demo' if is_demo_run else 'Real Audio Pipeline'}\n")
            f.write(f"Run Validity: {run_validity}\n")
            f.write(f"Segments assembled natively: {len(segments)}\n")
            f.write(f"Alignment Computed: {align_info.get('status', 'skipped')} (Cost: {align_info.get('dtw_normalized_cost', 'N/A')})\n")
            f.write("--- Metrics ---\n")
            f.write(f"Raw Pitch Correlation: {metrics.get('raw_metrics', {}).get('pitch_correlation')}\n")
            f.write(f"Aligned Pitch Correlation: {metrics.get('aligned_metrics', {}).get('pitch_correlation')}\n")
            f.write(f"Raw Energy Correlation: {metrics.get('raw_metrics', {}).get('energy_correlation')}\n")
            f.write(f"Aligned Energy Correlation: {metrics.get('aligned_metrics', {}).get('energy_correlation')}\n")
            f.write(f"MCD Score: {metrics.get('raw_metrics', {}).get('mcd_score')}\n")
            f.write("---\n")
            f.write(f"Major Limitations: Emotion mapping is heuristic. Time-warping waveform reconstruction not yet applied, but structural contours are aligned mathematically.\n")

        elapsed = time.time() - t_start
        print(f"\n[ORCHESTRATOR] Complete in {elapsed:.1f}s. Results saved to: {self.output_dir}")
