# ruff: noqa: E501
"""Generate export documents (PDF) using reportlab.

All documents are exporter-prepared drafts. Declarations, authority limits, and
official filing channels are clearly stated in each document.

Document types supported:
  proforma_invoice | commercial_invoice | packing_list |
  commercial_invoice_cum_packing_list | shipping_instruction |
  coo_application_data_sheet | export_document_checklist
"""

from __future__ import annotations

import hashlib
import io
import zipfile
from datetime import date
from typing import Any

from reportlab.lib import colors  # type: ignore[import-untyped]
from reportlab.lib.pagesizes import A4  # type: ignore[import-untyped]
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet  # type: ignore[import-untyped]
from reportlab.lib.units import mm  # type: ignore[import-untyped]
from reportlab.platypus import (  # type: ignore[import-untyped]
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

SUPPORTED_DOC_TYPES = {
    "proforma_invoice",
    "commercial_invoice",
    "packing_list",
    "commercial_invoice_cum_packing_list",
    "shipping_instruction",
    "coo_application_data_sheet",
    "export_document_checklist",
}

DISCLAIMER = (
    "DRAFT — Generated by ExportPilotAI. This document is prepared based on user-provided data. "
    "Verify all details with your CHA/customs broker, bank, buyer, and applicable government portal "
    "(ICEGATE/e-SANCHIT, DGFT, CBIC) before filing or shipment."
)

# ── colour palette ──────────────────────────────────────────────────────────
_DARK = colors.HexColor("#1a2035")
_GOLD = colors.HexColor("#c9a227")
_LIGHT_GREY = colors.HexColor("#f4f4f4")
_MID_GREY = colors.HexColor("#888888")
_BLACK = colors.black
_WHITE = colors.white


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    s: dict[str, ParagraphStyle] = {}
    s["title"] = ParagraphStyle("DocTitle", parent=base["Title"], fontSize=16, textColor=_DARK, spaceAfter=4)
    s["subtitle"] = ParagraphStyle("DocSubtitle", parent=base["Normal"], fontSize=9, textColor=_MID_GREY, spaceAfter=6)
    s["h2"] = ParagraphStyle("H2", parent=base["Heading2"], fontSize=10, textColor=_DARK, spaceBefore=8, spaceAfter=2)
    s["label"] = ParagraphStyle("Label", parent=base["Normal"], fontSize=7.5, textColor=_MID_GREY)
    s["value"] = ParagraphStyle("Value", parent=base["Normal"], fontSize=9, textColor=_DARK)
    s["small"] = ParagraphStyle("Small", parent=base["Normal"], fontSize=7.5, textColor=_MID_GREY)
    s["disclaimer"] = ParagraphStyle("Disclaimer", parent=base["Normal"], fontSize=7, textColor=_MID_GREY, borderPad=4, backColor=_LIGHT_GREY)
    s["bold"] = ParagraphStyle("Bold", parent=base["Normal"], fontSize=9, textColor=_DARK, fontName="Helvetica-Bold")
    s["normal"] = ParagraphStyle("Normal9", parent=base["Normal"], fontSize=9, textColor=_DARK)
    s["checklist_head"] = ParagraphStyle("CLHead", parent=base["Normal"], fontSize=10, textColor=_DARK, fontName="Helvetica-Bold", spaceBefore=8, spaceAfter=2)
    s["checklist_item"] = ParagraphStyle("CLItem", parent=base["Normal"], fontSize=9, textColor=_DARK, leftIndent=12, spaceAfter=2)
    return s


def _doc(buffer: io.BytesIO, title: str) -> SimpleDocTemplate:
    return SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
        title=title,
    )


def _header_table(exporter: dict, buyer: dict, shipment: dict, s: dict) -> list:
    """Two-column header: exporter left, buyer right."""
    def _block(label: str, lines: list[str]) -> list:
        out = [Paragraph(label, s["label"])]
        for line in lines:
            if line:
                out.append(Paragraph(line, s["value"]))
        return out

    exp = exporter
    byr = buyer
    exp_lines = [
        exp.get("company_name", ""),
        exp.get("address", ""),
        f"{exp.get('city', '')} {exp.get('state', '')} {exp.get('postal_code', '')}".strip(),
        exp.get("country", ""),
        f"IEC: {exp.get('iec', '—')}" if exp.get("iec") else "",
        f"GSTIN: {exp.get('gstin', '—')}" if exp.get("gstin") else "",
        f"Email: {exp.get('email', '')}" if exp.get("email") else "",
    ]
    byr_lines = [
        byr.get("buyer_name", ""),
        byr.get("buyer_address", ""),
        byr.get("buyer_country", ""),
    ]
    if byr.get("consignee_name") and byr.get("consignee_name") != byr.get("buyer_name"):
        byr_lines += ["", "Consignee:", byr.get("consignee_name", ""), byr.get("consignee_address", "")]

    exp_cell = _block("EXPORTER / SHIPPER", [l for l in exp_lines if l])
    byr_cell = _block("BUYER / CONSIGNEE", [l for l in byr_lines if l])
    tbl = Table([[exp_cell, byr_cell]], colWidths=[87 * mm, 87 * mm])
    tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOX", (0, 0), (0, 0), 0.5, _MID_GREY),
        ("BOX", (1, 0), (1, 0), 0.5, _MID_GREY),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return [tbl]


def _ref_table(pairs: list[tuple[str, str]], s: dict) -> list:
    """Key-value reference row table."""
    cells = [[Paragraph(k, s["label"]), Paragraph(v or "—", s["bold"])] for k, v in pairs if k]
    if not cells:
        return []
    tbl = Table(cells, colWidths=[50 * mm, 125 * mm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), _LIGHT_GREY),
        ("GRID", (0, 0), (-1, -1), 0.3, _MID_GREY),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ]))
    return [tbl]


def _item_table(items: list[dict], include_packing: bool, s: dict) -> list:
    """Line item table for invoice/packing list."""
    currency = ""  # set from outside if available

    base_headers = ["#", "Description", "HSN", "Qty", "Unit", "Unit Price", "Total Value"]
    pack_headers = ["Pkgs", "Pkg Type", "Net Wt (kg)", "Gross Wt (kg)"]
    headers = base_headers + (pack_headers if include_packing else [])

    col_widths_base = [8 * mm, 45 * mm, 18 * mm, 14 * mm, 12 * mm, 20 * mm, 22 * mm]
    col_widths_pack = [12 * mm, 15 * mm, 18 * mm, 18 * mm]
    col_widths = col_widths_base + (col_widths_pack if include_packing else [])

    header_row = [Paragraph(h, s["bold"]) for h in headers]
    rows = [header_row]

    totals: dict[str, float] = {"qty": 0, "total_value": 0, "pkg": 0, "net_wt": 0, "gross_wt": 0}

    for item in items:
        qty = item.get("quantity") or 0
        price = item.get("unit_price") or 0
        total = item.get("total_value") or (qty * price)
        totals["qty"] += qty
        totals["total_value"] += total

        row_base = [
            Paragraph(str(item.get("item_number", "")), s["normal"]),
            Paragraph(str(item.get("product_description") or ""), s["normal"]),
            Paragraph(str(item.get("hsn_code") or ""), s["normal"]),
            Paragraph(f"{qty:g}", s["normal"]),
            Paragraph(str(item.get("unit") or ""), s["normal"]),
            Paragraph(f"{price:,.2f}", s["normal"]),
            Paragraph(f"{total:,.2f}", s["normal"]),
        ]
        if include_packing:
            pkgs = item.get("package_count") or 0
            totals["pkg"] += pkgs
            nw = item.get("net_weight") or 0
            gw = item.get("gross_weight") or 0
            totals["net_wt"] += nw
            totals["gross_wt"] += gw
            row_base += [
                Paragraph(str(pkgs) if pkgs else "", s["normal"]),
                Paragraph(str(item.get("package_type") or ""), s["normal"]),
                Paragraph(f"{nw:g}" if nw else "", s["normal"]),
                Paragraph(f"{gw:g}" if gw else "", s["normal"]),
            ]
        rows.append(row_base)

    # Totals row
    total_cells_base = [
        Paragraph("", s["normal"]),
        Paragraph("TOTAL", s["bold"]),
        Paragraph("", s["normal"]),
        Paragraph(f"{totals['qty']:g}", s["bold"]),
        Paragraph("", s["normal"]),
        Paragraph("", s["normal"]),
        Paragraph(f"{totals['total_value']:,.2f}", s["bold"]),
    ]
    if include_packing:
        total_cells_base += [
            Paragraph(f"{int(totals['pkg'])}", s["bold"]),
            Paragraph("", s["normal"]),
            Paragraph(f"{totals['net_wt']:g}", s["bold"]),
            Paragraph(f"{totals['gross_wt']:g}", s["bold"]),
        ]
    rows.append(total_cells_base)

    tbl = Table(rows, colWidths=col_widths, repeatRows=1)
    n = len(rows)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), _WHITE),
        ("GRID", (0, 0), (-1, -1), 0.3, _MID_GREY),
        ("BACKGROUND", (0, n - 1), (-1, n - 1), _LIGHT_GREY),
        ("FONTNAME", (0, n - 1), (-1, n - 1), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, n - 2), [_WHITE, colors.HexColor("#f9f9f9")]),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return [tbl], totals


def _signature_block(declarations: dict, s: dict) -> list:
    name = declarations.get("authorized_signatory_name") or ""
    designation = declarations.get("authorized_signatory_designation") or ""
    place = declarations.get("place_of_issue") or ""
    dt = declarations.get("date_of_issue") or str(date.today())
    exporter_name = declarations.get("exporter_company_name") or ""
    return [
        Spacer(1, 8 * mm),
        HRFlowable(width="100%", thickness=0.5, color=_MID_GREY),
        Spacer(1, 4 * mm),
        Paragraph("For " + exporter_name, s["bold"]),
        Spacer(1, 12 * mm),
        Paragraph("_" * 40, s["normal"]),
        Paragraph(f"{name} | {designation}" if designation else name, s["value"]),
        Paragraph(f"Place: {place}  Date: {dt}", s["small"]),
        Paragraph("Authorised Signatory", s["label"]),
    ]


# ── Document generators ──────────────────────────────────────────────────────

def generate_proforma_invoice(data: dict[str, Any]) -> bytes:
    exporter = data.get("exporter", {})
    buyer = data.get("buyer", {})
    shipment = data.get("shipment", {})
    items = data.get("items", [])
    declarations = {**data.get("declarations", {}), "exporter_company_name": exporter.get("company_name", "")}

    buf = io.BytesIO()
    doc = _doc(buf, "PROFORMA INVOICE")
    s = _styles()
    story: list = []

    story.append(Paragraph("PROFORMA INVOICE", s["title"]))
    story.append(Paragraph("Subject to final commercial invoice on shipment.", s["subtitle"]))
    story.append(Spacer(1, 3 * mm))
    story += _header_table(exporter, buyer, shipment, s)
    story.append(Spacer(1, 3 * mm))
    story += _ref_table([
        ("Proforma Invoice No.", shipment.get("proforma_invoice_number") or shipment.get("invoice_number")),
        ("Proforma Invoice Date", shipment.get("proforma_invoice_date") or shipment.get("invoice_date")),
        ("Buyer Order / PO No.", shipment.get("buyer_order_number") or shipment.get("purchase_order_number")),
        ("Country of Origin", shipment.get("country_of_origin")),
        ("Country of Destination", shipment.get("country_of_final_destination")),
        ("Port of Loading", shipment.get("port_of_loading")),
        ("Port of Discharge", shipment.get("port_of_discharge")),
        ("Incoterm", f"{shipment.get('incoterm', '')} {shipment.get('port_of_discharge', '')} ({shipment.get('incoterms_version', 'Incoterms 2020')})"),
        ("Currency", shipment.get("currency")),
        ("Payment Terms", shipment.get("payment_terms")),
        ("Validity", shipment.get("validity") or "30 days from date"),
    ], s)
    story.append(Spacer(1, 4 * mm))

    item_tbl, totals = _item_table(items, include_packing=False, s=s)
    story += item_tbl
    story.append(Spacer(1, 2 * mm))
    cur = shipment.get("currency", "")
    story.append(Paragraph(f"<b>Total Invoice Value: {cur} {totals['total_value']:,.2f}</b>", s["value"]))

    if exporter.get("bank_name"):
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("Banking Details", s["h2"]))
        story += _ref_table([
            ("Bank Name", exporter.get("bank_name")),
            ("Account No.", exporter.get("bank_account")),
            ("IFSC/SWIFT", exporter.get("ifsc_swift")),
            ("AD Code", exporter.get("ad_code")),
        ], s)

    story += _signature_block(declarations, s)
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))

    doc.build(story)
    return buf.getvalue()


def generate_commercial_invoice(data: dict[str, Any]) -> bytes:
    exporter = data.get("exporter", {})
    buyer = data.get("buyer", {})
    shipment = data.get("shipment", {})
    items = data.get("items", [])
    declarations = {**data.get("declarations", {}), "exporter_company_name": exporter.get("company_name", "")}

    buf = io.BytesIO()
    doc = _doc(buf, "COMMERCIAL INVOICE")
    s = _styles()
    story: list = []

    story.append(Paragraph("COMMERCIAL INVOICE", s["title"]))
    story.append(Spacer(1, 3 * mm))
    story += _header_table(exporter, buyer, shipment, s)
    story.append(Spacer(1, 3 * mm))
    story += _ref_table([
        ("Invoice No.", shipment.get("invoice_number")),
        ("Invoice Date", shipment.get("invoice_date")),
        ("Buyer Order / PO No.", shipment.get("buyer_order_number") or shipment.get("purchase_order_number")),
        ("Shipment Reference", shipment.get("shipment_reference")),
        ("Country of Origin", shipment.get("country_of_origin")),
        ("Country of Final Destination", shipment.get("country_of_final_destination")),
        ("Port of Loading", shipment.get("port_of_loading")),
        ("Port of Discharge", shipment.get("port_of_discharge")),
        ("Incoterm", f"{shipment.get('incoterm', '')} {shipment.get('port_of_discharge', '')} ({shipment.get('incoterms_version', 'Incoterms 2020')})"),
        ("Mode of Transport", shipment.get("mode_of_transport", "Sea").title()),
        ("Currency", shipment.get("currency")),
        ("Payment Terms", shipment.get("payment_terms")),
        ("Marks & Numbers", shipment.get("marks_and_numbers")),
    ], s)
    story.append(Spacer(1, 4 * mm))

    item_tbl, totals = _item_table(items, include_packing=False, s=s)
    story += item_tbl
    story.append(Spacer(1, 2 * mm))

    cur = shipment.get("currency", "")
    packing = data.get("packing", {})
    freight = packing.get("freight") or 0
    insurance = packing.get("insurance") or 0
    grand = totals["total_value"] + freight + insurance
    if freight or insurance:
        story += _ref_table([
            ("FOB Value", f"{cur} {totals['total_value']:,.2f}"),
            ("Freight", f"{cur} {freight:,.2f}" if freight else "—"),
            ("Insurance", f"{cur} {insurance:,.2f}" if insurance else "—"),
            ("Total Invoice Value (CIF)", f"{cur} {grand:,.2f}"),
        ], s)
    else:
        story.append(Paragraph(f"<b>Total Invoice Value: {cur} {grand:,.2f}</b>", s["value"]))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Declaration", s["h2"]))
    decl_text = declarations.get("declaration_of_origin") or (
        f"We hereby certify that the goods described in this invoice are of Indian origin "
        f"and that this invoice is true and correct."
    )
    story.append(Paragraph(decl_text, s["normal"]))

    story += _signature_block(declarations, s)
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))

    doc.build(story)
    return buf.getvalue()


def generate_packing_list(data: dict[str, Any]) -> bytes:
    exporter = data.get("exporter", {})
    buyer = data.get("buyer", {})
    shipment = data.get("shipment", {})
    items = data.get("items", [])
    packing = data.get("packing", {})
    declarations = {**data.get("declarations", {}), "exporter_company_name": exporter.get("company_name", "")}

    buf = io.BytesIO()
    doc = _doc(buf, "PACKING LIST")
    s = _styles()
    story: list = []

    story.append(Paragraph("PACKING LIST", s["title"]))
    story.append(Spacer(1, 3 * mm))
    story += _header_table(exporter, buyer, shipment, s)
    story.append(Spacer(1, 3 * mm))
    story += _ref_table([
        ("Invoice No.", shipment.get("invoice_number")),
        ("Invoice Date", shipment.get("invoice_date")),
        ("Packing List Date", shipment.get("invoice_date")),
        ("Port of Loading", shipment.get("port_of_loading")),
        ("Port of Discharge", shipment.get("port_of_discharge")),
        ("Mode of Transport", shipment.get("mode_of_transport", "Sea").title()),
        ("Marks & Numbers", shipment.get("marks_and_numbers")),
        ("Container No.", shipment.get("container_number")),
        ("Seal No.", shipment.get("seal_number")),
    ], s)
    story.append(Spacer(1, 4 * mm))

    item_tbl, totals = _item_table(items, include_packing=True, s=s)
    story += item_tbl
    story.append(Spacer(1, 2 * mm))

    total_pkgs = packing.get("total_packages") or int(totals["pkg"])
    total_nw = packing.get("total_net_weight") or totals["net_wt"]
    total_gw = packing.get("total_gross_weight") or totals["gross_wt"]
    story += _ref_table([
        ("Total Packages", f"{total_pkgs} {packing.get('package_type', '')}".strip()),
        ("Total Net Weight", f"{total_nw:g} kg"),
        ("Total Gross Weight", f"{total_gw:g} kg"),
        ("Total Volume", f"{packing.get('total_volume', '')} CBM" if packing.get("total_volume") else "—"),
    ], s)

    story += _signature_block(declarations, s)
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))

    doc.build(story)
    return buf.getvalue()


def generate_invoice_cum_packing_list(data: dict[str, Any]) -> bytes:
    exporter = data.get("exporter", {})
    buyer = data.get("buyer", {})
    shipment = data.get("shipment", {})
    items = data.get("items", [])
    packing = data.get("packing", {})
    declarations = {**data.get("declarations", {}), "exporter_company_name": exporter.get("company_name", "")}

    buf = io.BytesIO()
    doc = _doc(buf, "COMMERCIAL INVOICE-CUM-PACKING LIST")
    s = _styles()
    story: list = []

    story.append(Paragraph("COMMERCIAL INVOICE-CUM-PACKING LIST", s["title"]))
    story.append(Spacer(1, 3 * mm))
    story += _header_table(exporter, buyer, shipment, s)
    story.append(Spacer(1, 3 * mm))
    story += _ref_table([
        ("Invoice No.", shipment.get("invoice_number")),
        ("Invoice Date", shipment.get("invoice_date")),
        ("Buyer PO No.", shipment.get("buyer_order_number")),
        ("Country of Origin", shipment.get("country_of_origin")),
        ("Port of Loading", shipment.get("port_of_loading")),
        ("Port of Discharge", shipment.get("port_of_discharge")),
        ("Incoterm", f"{shipment.get('incoterm', '')} {shipment.get('port_of_discharge', '')} ({shipment.get('incoterms_version', 'Incoterms 2020')})"),
        ("Currency", shipment.get("currency")),
        ("Payment Terms", shipment.get("payment_terms")),
        ("Marks & Numbers", shipment.get("marks_and_numbers")),
    ], s)
    story.append(Spacer(1, 4 * mm))

    item_tbl, totals = _item_table(items, include_packing=True, s=s)
    story += item_tbl
    story.append(Spacer(1, 2 * mm))

    cur = shipment.get("currency", "")
    total_pkgs = packing.get("total_packages") or int(totals["pkg"])
    total_nw = packing.get("total_net_weight") or totals["net_wt"]
    total_gw = packing.get("total_gross_weight") or totals["gross_wt"]
    story += _ref_table([
        ("Total Invoice Value", f"{cur} {totals['total_value']:,.2f}"),
        ("Total Packages", f"{total_pkgs} {packing.get('package_type', '')}".strip()),
        ("Total Net Weight", f"{total_nw:g} kg"),
        ("Total Gross Weight", f"{total_gw:g} kg"),
    ], s)

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Declaration", s["h2"]))
    story.append(Paragraph("We hereby certify that the goods described herein are of Indian origin and that this invoice is true and correct.", s["normal"]))
    story += _signature_block(declarations, s)
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))

    doc.build(story)
    return buf.getvalue()


def generate_shipping_instruction(data: dict[str, Any]) -> bytes:
    exporter = data.get("exporter", {})
    buyer = data.get("buyer", {})
    shipment = data.get("shipment", {})
    items = data.get("items", [])
    packing = data.get("packing", {})

    buf = io.BytesIO()
    doc = _doc(buf, "SHIPPING INSTRUCTION DRAFT")
    s = _styles()
    story: list = []

    story.append(Paragraph("SHIPPING INSTRUCTION — DRAFT", s["title"]))
    story.append(Paragraph(
        "This is a shipping instruction draft prepared for your CHA / Customs Broker / Freight Forwarder. "
        "It is NOT a Bill of Lading or Airway Bill. The official Bill of Lading / Airway Bill is issued by the carrier or freight forwarder.",
        s["subtitle"]
    ))
    story.append(Spacer(1, 4 * mm))

    story += _ref_table([
        ("Shipper / Exporter", exporter.get("company_name")),
        ("Shipper Address", f"{exporter.get('address', '')} {exporter.get('city', '')} {exporter.get('state', '')} {exporter.get('country', '')}".strip()),
        ("IEC", exporter.get("iec")),
        ("Consignee", buyer.get("consignee_name") or buyer.get("buyer_name")),
        ("Consignee Address", buyer.get("consignee_address") or buyer.get("buyer_address")),
        ("Notify Party", buyer.get("notify_party") or buyer.get("buyer_name")),
        ("Invoice No.", shipment.get("invoice_number")),
        ("Invoice Date", shipment.get("invoice_date")),
        ("Country of Origin", shipment.get("country_of_origin")),
        ("Port of Loading", shipment.get("port_of_loading")),
        ("Port of Discharge", shipment.get("port_of_discharge")),
        ("Final Destination", shipment.get("final_destination") or shipment.get("country_of_final_destination")),
        ("Mode of Transport", shipment.get("mode_of_transport", "Sea").title()),
        ("Incoterm / Freight Terms", f"{shipment.get('incoterm', '')} {shipment.get('port_of_discharge', '')} ({shipment.get('incoterms_version', 'Incoterms 2020')})"),
        ("Expected Shipment Date", shipment.get("expected_shipment_date")),
        ("Vessel / Flight No.", shipment.get("vessel_flight_number")),
        ("Container No.", shipment.get("container_number")),
        ("Seal No.", shipment.get("seal_number")),
    ], s)

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Cargo Details", s["h2"]))

    total_pkgs = packing.get("total_packages") or sum(i.get("package_count") or 0 for i in items)
    total_nw = packing.get("total_net_weight") or sum(i.get("net_weight") or 0 for i in items)
    total_gw = packing.get("total_gross_weight") or sum(i.get("gross_weight") or 0 for i in items)
    descriptions = "; ".join(i.get("product_description", "") for i in items if i.get("product_description"))
    hsns = ", ".join(str(i.get("hsn_code", "")) for i in items if i.get("hsn_code"))

    story += _ref_table([
        ("Commodity Description", descriptions),
        ("HSN Code(s)", hsns),
        ("Total Packages", f"{total_pkgs} {packing.get('package_type', '')}".strip()),
        ("Total Net Weight", f"{total_nw:g} kg"),
        ("Total Gross Weight", f"{total_gw:g} kg"),
        ("Total Volume", f"{packing.get('total_volume', '')} CBM" if packing.get("total_volume") else "—"),
        ("Shipping Marks", shipment.get("marks_and_numbers")),
        ("Special Handling", packing.get("special_handling")),
    ], s)

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Documents to be prepared by CHA/Freight Forwarder", s["h2"]))
    for doc_item in [
        "Shipping Bill / Bill of Export — to be filed on ICEGATE by CHA/Customs Broker",
        "Bill of Lading / Airway Bill — to be issued by carrier/freight forwarder",
        "Export General Manifest (EGM) — filed by carrier/stevedore",
        "Insurance Certificate (if applicable)",
    ]:
        story.append(Paragraph(f"• {doc_item}", s["checklist_item"]))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))

    doc.build(story)
    return buf.getvalue()


def generate_coo_application_data_sheet(data: dict[str, Any]) -> bytes:
    exporter = data.get("exporter", {})
    buyer = data.get("buyer", {})
    shipment = data.get("shipment", {})
    items = data.get("items", [])

    buf = io.BytesIO()
    doc = _doc(buf, "CERTIFICATE OF ORIGIN — APPLICATION DATA SHEET")
    s = _styles()
    story: list = []

    story.append(Paragraph("CERTIFICATE OF ORIGIN — APPLICATION DATA SHEET", s["title"]))
    story.append(Paragraph(
        "This is an application support draft prepared to assist in applying for a Certificate of Origin. "
        "The official Certificate of Origin must be issued through DGFT/eCoO portal or an authorized issuing agency "
        "(Export Promotion Councils, Trade Bodies, Chambers of Commerce). This document does NOT constitute an official Certificate of Origin.",
        s["subtitle"]
    ))
    story.append(Spacer(1, 4 * mm))

    story += _ref_table([
        ("Exporter / Manufacturer", exporter.get("company_name")),
        ("Exporter Address", f"{exporter.get('address', '')} {exporter.get('city', '')} {exporter.get('state', '')} {exporter.get('country', '')}".strip()),
        ("IEC", exporter.get("iec")),
        ("GSTIN", exporter.get("gstin")),
        ("Buyer / Importer", buyer.get("buyer_name")),
        ("Buyer Address", buyer.get("buyer_address")),
        ("Buyer Country", buyer.get("buyer_country")),
        ("Invoice No.", shipment.get("invoice_number")),
        ("Invoice Date", shipment.get("invoice_date")),
        ("Country of Origin", shipment.get("country_of_origin", "India")),
        ("Country of Destination", shipment.get("country_of_final_destination")),
        ("Port of Loading", shipment.get("port_of_loading")),
        ("Port of Discharge", shipment.get("port_of_discharge")),
        ("Incoterm", f"{shipment.get('incoterm', '')} {shipment.get('port_of_discharge', '')}"),
    ], s)

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Goods Description", s["h2"]))
    item_tbl, totals = _item_table(items, include_packing=False, s=s)
    story += item_tbl

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Origin Declaration", s["h2"]))
    story.append(Paragraph(
        "The exporter of the products covered by this document declares that, except where otherwise clearly indicated, "
        "these products are of Indian preferential origin as defined in applicable rules of origin criteria.",
        s["normal"]
    ))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Supporting Documents Checklist for CoO Application", s["h2"]))
    for item in [
        "Commercial Invoice",
        "Packing List",
        "Shipping Bill (if post-shipment CoO) — filed on ICEGATE by CHA",
        "Bill of Lading / Airway Bill (if post-shipment) — issued by carrier",
        "Manufacturing process / value addition details (if required by issuing agency)",
        "IEC copy",
        "GST registration certificate",
    ]:
        story.append(Paragraph(f"☐  {item}", s["checklist_item"]))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        "Apply for Certificate of Origin at: DGFT eCoO portal (https://ecooftp.dgft.gov.in) or applicable "
        "Export Promotion Council / Chamber of Commerce for the commodity and destination country.",
        s["small"]
    ))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))

    doc.build(story)
    return buf.getvalue()


def generate_export_document_checklist(data: dict[str, Any]) -> bytes:
    shipment = data.get("shipment", {})
    items = data.get("items", [])

    buf = io.BytesIO()
    doc = _doc(buf, "EXPORT DOCUMENT CHECKLIST")
    s = _styles()
    story: list = []

    mode = (shipment.get("mode_of_transport") or "sea").lower()
    dest = shipment.get("country_of_final_destination") or "destination country"
    hsns = [str(i.get("hsn_code", "")) for i in items if i.get("hsn_code")]

    story.append(Paragraph("EXPORT DOCUMENT CHECKLIST", s["title"]))
    story.append(Paragraph(
        f"Reference: Invoice {shipment.get('invoice_number', '—')} | Destination: {dest} | Mode: {mode.title()}",
        s["subtitle"]
    ))
    story.append(Paragraph(
        "This checklist is guidance only. Actual document requirements depend on product, destination country, "
        "buyer terms, applicable trade agreements, and your CHA/customs broker. Always verify before shipment.",
        s["subtitle"]
    ))
    story.append(Spacer(1, 4 * mm))

    def _section(title: str, items_list: list[tuple[str, str]]) -> list:
        out = [Paragraph(title, s["checklist_head"])]
        for label, note in items_list:
            text = f"☐  <b>{label}</b>"
            if note:
                text += f" <font color='grey' size='8'>({note})</font>"
            out.append(Paragraph(text, s["checklist_item"]))
        return out

    story += _section("Core Export Documents", [
        ("Commercial Invoice", "Prepared by exporter — generated by this tool"),
        ("Packing List", "Prepared by exporter — generated by this tool"),
        ("Shipping Bill / Bill of Export", "Filed on ICEGATE/e-SANCHIT by exporter/CHA — NOT generated by this tool"),
        ("Bill of Lading / Airway Bill", "Issued by carrier/freight forwarder — NOT generated by this tool"),
        ("Export General Manifest (EGM)", "Filed by carrier/stevedore after shipment"),
    ])

    story += _section("Regulatory & Compliance (India)", [
        ("IEC (Importer Exporter Code)", "Mandatory — issued by DGFT (https://dgft.gov.in)"),
        ("GST Registration / LUT / Bond", "LUT/Bond required for zero-rated supply without IGST payment"),
        ("AD Code registration at customs", "Required for bank realization (registered by your bank at port)"),
        ("e-SANCHIT document upload", "Supporting documents uploaded on ICEGATE e-SANCHIT before Shipping Bill filing"),
    ])

    story += _section("Frequently Required Conditional Documents", [
        ("Certificate of Origin", "Required by buyer or for preferential tariff — apply via DGFT/eCoO or authorized agency"),
        ("Phytosanitary Certificate", "Required for plants, plant products — issued by Plant Quarantine authority"),
        ("Fumigation Certificate", "If buyer/destination country requires fumigation of packing/cargo"),
        ("Inspection Certificate", "If buyer/L/C stipulates pre-shipment inspection"),
        ("Insurance Certificate", "For CIF/CIP shipments or as required by buyer/L/C"),
        ("MSDS / Dangerous Goods Declaration", "For hazardous/chemical cargo — required by carrier and customs"),
    ])

    story += _section("Product-Specific Documents (check for your commodity)", [
        ("FSSAI Certificate / NOC", "For food products, edible commodities"),
        ("APEDA Certificate / Registration", "For agricultural/processed food exports"),
        ("Plant Quarantine Certificate", "For seeds, plants, plant material"),
        ("Drug / Pharma Export License", "For pharmaceutical, drug, or controlled substance exports"),
        ("Export License (SCOMET/Strategic)", "For strategic goods, dual-use items, defence items — DGFT"),
        ("Quality / Lab Test Certificate", "If buyer L/C or destination country requires specific quality certification"),
    ])

    story += _section("Bank & Financial Documents", [
        ("Letter of Credit (if applicable)", "Buyer's bank instrument — obtain before shipment"),
        ("Bank Realisation Certificate (BRC/eBRC)", "Post-shipment — obtained from bank after forex realization"),
        ("ECGC Coverage (if applicable)", "Export credit insurance — ECGC India"),
    ])

    if hsns:
        story.append(Spacer(1, 3 * mm))
        story.append(Paragraph(f"HSN codes in this shipment: {', '.join(hsns)}", s["small"]))
        story.append(Paragraph("Check incentive eligibility for these HSN codes in the Incentive Finder module.", s["small"]))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))
    doc.build(story)
    return buf.getvalue()


# ── Public dispatcher ────────────────────────────────────────────────────────

_GENERATORS = {
    "proforma_invoice": generate_proforma_invoice,
    "commercial_invoice": generate_commercial_invoice,
    "packing_list": generate_packing_list,
    "commercial_invoice_cum_packing_list": generate_invoice_cum_packing_list,
    "shipping_instruction": generate_shipping_instruction,
    "coo_application_data_sheet": generate_coo_application_data_sheet,
    "export_document_checklist": generate_export_document_checklist,
}

_DOC_FILENAMES = {
    "proforma_invoice": "Proforma_Invoice",
    "commercial_invoice": "Commercial_Invoice",
    "packing_list": "Packing_List",
    "commercial_invoice_cum_packing_list": "Invoice_cum_Packing_List",
    "shipping_instruction": "Shipping_Instruction_Draft",
    "coo_application_data_sheet": "CoO_Application_Data_Sheet",
    "export_document_checklist": "Export_Document_Checklist",
}


def generate_document(doc_type: str, data: dict[str, Any]) -> tuple[bytes, str]:
    """Generate one document. Returns (pdf_bytes, suggested_filename)."""
    if doc_type not in _GENERATORS:
        raise ValueError(f"Unsupported document type: {doc_type}")
    pdf_bytes = _GENERATORS[doc_type](data)
    inv = (data.get("shipment") or {}).get("invoice_number") or "draft"
    filename = f"{_DOC_FILENAMES[doc_type]}_{inv}.pdf"
    return pdf_bytes, filename


def generate_zip(docs: list[tuple[str, bytes]]) -> bytes:
    """Pack (filename, bytes) list into a ZIP."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname, data in docs:
            zf.writestr(fname, data)
    return buf.getvalue()


def checksum(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:16]
